// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: artiststn.proto

package eu.trentorise.smartcampus.service.artiststn.data.message;

public final class Artiststn {
  private Artiststn() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ArtistOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required string name = 2;
    boolean hasName();
    String getName();
    
    // optional string description = 3;
    boolean hasDescription();
    String getDescription();
    
    // optional string link = 4;
    boolean hasLink();
    String getLink();
    
    // optional string img = 5;
    boolean hasImg();
    String getImg();
    
    // repeated string times = 6;
    java.util.List<String> getTimesList();
    int getTimesCount();
    String getTimes(int index);
    
    // required .it.sayservice.platform.core.message.POI poi = 7;
    boolean hasPoi();
    it.sayservice.platform.core.message.Core.POI getPoi();
    it.sayservice.platform.core.message.Core.POIOrBuilder getPoiOrBuilder();
  }
  public static final class Artist extends
      com.google.protobuf.GeneratedMessage
      implements ArtistOrBuilder {
    // Use Artist.newBuilder() to construct.
    private Artist(Builder builder) {
      super(builder);
    }
    private Artist(boolean noInit) {}
    
    private static final Artist defaultInstance;
    public static Artist getDefaultInstance() {
      return defaultInstance;
    }
    
    public Artist getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.internal_static_eu_trentorise_smartcampus_service_artiststn_data_message_Artist_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.internal_static_eu_trentorise_smartcampus_service_artiststn_data_message_Artist_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string link = 4;
    public static final int LINK_FIELD_NUMBER = 4;
    private java.lang.Object link_;
    public boolean hasLink() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getLink() {
      java.lang.Object ref = link_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          link_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLinkBytes() {
      java.lang.Object ref = link_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        link_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string img = 5;
    public static final int IMG_FIELD_NUMBER = 5;
    private java.lang.Object img_;
    public boolean hasImg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getImg() {
      java.lang.Object ref = img_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          img_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getImgBytes() {
      java.lang.Object ref = img_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        img_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string times = 6;
    public static final int TIMES_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList times_;
    public java.util.List<String>
        getTimesList() {
      return times_;
    }
    public int getTimesCount() {
      return times_.size();
    }
    public String getTimes(int index) {
      return times_.get(index);
    }
    
    // required .it.sayservice.platform.core.message.POI poi = 7;
    public static final int POI_FIELD_NUMBER = 7;
    private it.sayservice.platform.core.message.Core.POI poi_;
    public boolean hasPoi() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public it.sayservice.platform.core.message.Core.POI getPoi() {
      return poi_;
    }
    public it.sayservice.platform.core.message.Core.POIOrBuilder getPoiOrBuilder() {
      return poi_;
    }
    
    private void initFields() {
      id_ = "";
      name_ = "";
      description_ = "";
      link_ = "";
      img_ = "";
      times_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      poi_ = it.sayservice.platform.core.message.Core.POI.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPoi()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPoi().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getLinkBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getImgBytes());
      }
      for (int i = 0; i < times_.size(); i++) {
        output.writeBytes(6, times_.getByteString(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(7, poi_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getLinkBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getImgBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < times_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(times_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTimesList().size();
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, poi_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.ArtistOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.internal_static_eu_trentorise_smartcampus_service_artiststn_data_message_Artist_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.internal_static_eu_trentorise_smartcampus_service_artiststn_data_message_Artist_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPoiFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        link_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        img_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        times_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (poiBuilder_ == null) {
          poi_ = it.sayservice.platform.core.message.Core.POI.getDefaultInstance();
        } else {
          poiBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist build() {
        eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist buildPartial() {
        eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist result = new eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.link_ = link_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.img_ = img_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          times_ = new com.google.protobuf.UnmodifiableLazyStringList(
              times_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.times_ = times_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        if (poiBuilder_ == null) {
          result.poi_ = poi_;
        } else {
          result.poi_ = poiBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist) {
          return mergeFrom((eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist other) {
        if (other == eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasLink()) {
          setLink(other.getLink());
        }
        if (other.hasImg()) {
          setImg(other.getImg());
        }
        if (!other.times_.isEmpty()) {
          if (times_.isEmpty()) {
            times_ = other.times_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureTimesIsMutable();
            times_.addAll(other.times_);
          }
          onChanged();
        }
        if (other.hasPoi()) {
          mergePoi(other.getPoi());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasPoi()) {
          
          return false;
        }
        if (!getPoi().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              description_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              link_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              img_ = input.readBytes();
              break;
            }
            case 50: {
              ensureTimesIsMutable();
              times_.add(input.readBytes());
              break;
            }
            case 58: {
              it.sayservice.platform.core.message.Core.POI.Builder subBuilder = it.sayservice.platform.core.message.Core.POI.newBuilder();
              if (hasPoi()) {
                subBuilder.mergeFrom(getPoi());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPoi(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional string description = 3;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
      }
      
      // optional string link = 4;
      private java.lang.Object link_ = "";
      public boolean hasLink() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getLink() {
        java.lang.Object ref = link_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          link_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLink(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        link_ = value;
        onChanged();
        return this;
      }
      public Builder clearLink() {
        bitField0_ = (bitField0_ & ~0x00000008);
        link_ = getDefaultInstance().getLink();
        onChanged();
        return this;
      }
      void setLink(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        link_ = value;
        onChanged();
      }
      
      // optional string img = 5;
      private java.lang.Object img_ = "";
      public boolean hasImg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getImg() {
        java.lang.Object ref = img_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          img_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setImg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        img_ = value;
        onChanged();
        return this;
      }
      public Builder clearImg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        img_ = getDefaultInstance().getImg();
        onChanged();
        return this;
      }
      void setImg(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        img_ = value;
        onChanged();
      }
      
      // repeated string times = 6;
      private com.google.protobuf.LazyStringList times_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTimesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          times_ = new com.google.protobuf.LazyStringArrayList(times_);
          bitField0_ |= 0x00000020;
         }
      }
      public java.util.List<String>
          getTimesList() {
        return java.util.Collections.unmodifiableList(times_);
      }
      public int getTimesCount() {
        return times_.size();
      }
      public String getTimes(int index) {
        return times_.get(index);
      }
      public Builder setTimes(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTimesIsMutable();
        times_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addTimes(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTimesIsMutable();
        times_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllTimes(
          java.lang.Iterable<String> values) {
        ensureTimesIsMutable();
        super.addAll(values, times_);
        onChanged();
        return this;
      }
      public Builder clearTimes() {
        times_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      void addTimes(com.google.protobuf.ByteString value) {
        ensureTimesIsMutable();
        times_.add(value);
        onChanged();
      }
      
      // required .it.sayservice.platform.core.message.POI poi = 7;
      private it.sayservice.platform.core.message.Core.POI poi_ = it.sayservice.platform.core.message.Core.POI.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          it.sayservice.platform.core.message.Core.POI, it.sayservice.platform.core.message.Core.POI.Builder, it.sayservice.platform.core.message.Core.POIOrBuilder> poiBuilder_;
      public boolean hasPoi() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public it.sayservice.platform.core.message.Core.POI getPoi() {
        if (poiBuilder_ == null) {
          return poi_;
        } else {
          return poiBuilder_.getMessage();
        }
      }
      public Builder setPoi(it.sayservice.platform.core.message.Core.POI value) {
        if (poiBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          poi_ = value;
          onChanged();
        } else {
          poiBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder setPoi(
          it.sayservice.platform.core.message.Core.POI.Builder builderForValue) {
        if (poiBuilder_ == null) {
          poi_ = builderForValue.build();
          onChanged();
        } else {
          poiBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder mergePoi(it.sayservice.platform.core.message.Core.POI value) {
        if (poiBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              poi_ != it.sayservice.platform.core.message.Core.POI.getDefaultInstance()) {
            poi_ =
              it.sayservice.platform.core.message.Core.POI.newBuilder(poi_).mergeFrom(value).buildPartial();
          } else {
            poi_ = value;
          }
          onChanged();
        } else {
          poiBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder clearPoi() {
        if (poiBuilder_ == null) {
          poi_ = it.sayservice.platform.core.message.Core.POI.getDefaultInstance();
          onChanged();
        } else {
          poiBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      public it.sayservice.platform.core.message.Core.POI.Builder getPoiBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getPoiFieldBuilder().getBuilder();
      }
      public it.sayservice.platform.core.message.Core.POIOrBuilder getPoiOrBuilder() {
        if (poiBuilder_ != null) {
          return poiBuilder_.getMessageOrBuilder();
        } else {
          return poi_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          it.sayservice.platform.core.message.Core.POI, it.sayservice.platform.core.message.Core.POI.Builder, it.sayservice.platform.core.message.Core.POIOrBuilder> 
          getPoiFieldBuilder() {
        if (poiBuilder_ == null) {
          poiBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              it.sayservice.platform.core.message.Core.POI, it.sayservice.platform.core.message.Core.POI.Builder, it.sayservice.platform.core.message.Core.POIOrBuilder>(
                  poi_,
                  getParentForChildren(),
                  isClean());
          poi_ = null;
        }
        return poiBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.service.artiststn.data.message.Artist)
    }
    
    static {
      defaultInstance = new Artist(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.service.artiststn.data.message.Artist)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_service_artiststn_data_message_Artist_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_service_artiststn_data_message_Artist_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017artiststn.proto\0228eu.trentorise.smartca" +
      "mpus.service.artiststn.data.message\032\ncor" +
      "e.proto\"\230\001\n\006Artist\022\n\n\002id\030\001 \002(\t\022\014\n\004name\030\002" +
      " \002(\t\022\023\n\013description\030\003 \001(\t\022\014\n\004link\030\004 \001(\t\022" +
      "\013\n\003img\030\005 \001(\t\022\r\n\005times\030\006 \003(\t\0225\n\003poi\030\007 \002(\013" +
      "2(.it.sayservice.platform.core.message.P" +
      "OI"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_eu_trentorise_smartcampus_service_artiststn_data_message_Artist_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_eu_trentorise_smartcampus_service_artiststn_data_message_Artist_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_service_artiststn_data_message_Artist_descriptor,
              new java.lang.String[] { "Id", "Name", "Description", "Link", "Img", "Times", "Poi", },
              eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist.class,
              eu.trentorise.smartcampus.service.artiststn.data.message.Artiststn.Artist.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          it.sayservice.platform.core.message.Core.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
